[options]
admin_passwd = $pbkdf2-sha512$600000$Zcy59/5fS4kRohQihDBmzA$/ekt8t5QwxumUTbhKw4vUCu1qioHhgVC1jzl7ecO6LO66hlQ7P8WtnLLN9jVwSVBeUbq/VKR4nBfp6jZzIs1EA

# Log file configuration
logfile = /var/log/odoo/odoo.log
log_level = info

addons_path = /mnt/extra-addons,/mnt/extra-addons/double_bill

[options]
# Log file configuration
logfile = /var/log/odoo/odoo.log
log_level = info


# admin_passwd = youradminpassword
addons_path = /mnt/extra-addons/enterprise-addons,/mnt/extra-addons/extra-addons,/mnt/extra-addons/your-addons
data_dir = /var/lib/odoo
db_host = postgres_14_09
db_port = 5432
db_user = youruserplease
db_password = yourpassplease
http_port = 8069
logrotate = True
proxy_mode = True
db_name = False
server_wide_modules = base,web